[package]
name = "odbc-cli"
version = "0.0.1"
edition = "2021"

[dependencies]
odbc-api = "8.1.2"
strum_macros = "0.26.4"
csv = "1.3.0"
clap = { version = "4.5.11", features = ["derive"] }
serde_json = "1.0.121"
