[package]
name = "odbc-cli"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive", "env"] }
# odbc-secrets-lib = { path = "../odbc-secrets-lib" }
odbc-secrets-lib = { git = "https://github.com/SamuelMarks/odbc-secrets-lib" }
strum_macros = "0.26.4"
